const express = require("express");
const Router = express.Router();
const { signup } = require("../controller/UserAuth");
const { login } = require("../controller/UserAuth");
const { AddTasks } = require("../controller/Tasks");
const { fetchtasks } = require("../controller/Tasks");
const { deletetask } = require("../controller/Tasks");
const { handlecheck } = require("../controller/Tasks");
const { handleforgot } = require("../controller/UserAuth");
const { resetpass } = require("../controller/UserAuth");
Router.post("/signup", signup);
Router.post("/login", login);
Router.post("/addtask", AddTasks);
Router.get("/fetchtasks", fetchtasks);
Router.post("/deletetask", deletetask);
Router.post("/checktask", handlecheck);
Router.post("/forgotpass", handleforgot);
Router.post("/reset-password/:id", resetpass);
module.exports = { Router };
